id: https://example.org/predict/schema
name: predict
title: Predict Data Model
description: ''
license: CC BY-NC 4.0
version: 1.3
prefixes:
  predict: https://example.org/predict/
  linkml: https://w3id.org/linkml/
  ncit: http://purl.obolibrary.org/obo/NCIT_
default_prefix: predict
default_range: string
imports:
- linkml:types
- slots
- enums
subsets:
  md:
    name: md
    title: Monogenic Diabetes
    description: The MD view of the PREDICT data model represents consensus data modeling by an international group of monogenic diabetes experts and is maintained by Data for the Common Good (D4CG) at the University of Chicago. It is based on the collective requirements of its contributors.
classes:
  SubjectCharacteristics:
    slots:
    - honest_broker_subject_id
    - data_contributor_id
    - data_source
    - last_known_survival_status
    - age_last_contact
    - age_last_contact_normalized
    - age_last_contact_unit
    - age_last_contact_precision
    comments:
    - 'D4CGNote: One row per subject.'
    annotations:
      domain: demographics
  Timing:
    slots:
    - honest_broker_subject_id
    - subject_characteristics
    - timepoint
    - timing_age_at
    - timing_age_at_normalized
    - age_unit
    - age_precision
    comments:
    - 'D4CGNote: One row per subject per timepoint.'
    annotations:
      domain: demographics
  FamilyMedicalHistory:
    slots:
    - honest_broker_subject_id
    - subject_characteristics
    - relation_honest_broker_subject_id
    - relation
    - condition
    - source
    comments:
    - 'D4CGNote: One row per subject per relation per condition.'
    - '(md_v1.3) ConsortiumNote: Only enter family members who have a history of dysglycemia.'
    annotations:
      domain: demographics
  Demographics:
    slots:
    - honest_broker_subject_id
    - subject_characteristics
    - sex
    - ethnicity
    - race
    comments:
    - 'D4CGNote: One row per subject.'
    annotations:
      domain: demographics
  MedicalHistory:
    slots:
    - honest_broker_subject_id
    - subject_characteristics
    - age_at
    - age_at_normalized
    - age_unit
    - age_precision
    - medical_history_condition
    - condition_other
    - condition_code
    - code_system
    comments:
    - 'D4CGNote: One row per subject per condition.'
    annotations:
      domain: demographics
  Biometrics:
    slots:
    - honest_broker_subject_id
    - subject_characteristics
    - age_at
    - age_at_normalized
    - age_unit
    - age_precision
    - measurement_type
    - measurement_numeric
    - measurement_unit
    - z_score
    comments:
    - 'D4CGNote: One row per subject per biometric measurement.'
    annotations:
      domain: testing
  Biospecimen:
    slots:
    - honest_broker_subject_id
    - subject_characteristics
    - sample_type
    comments:
    - 'D4CGNote: One row per subject per sample type.'
    annotations:
      domain: testing
  GeneticAnalysis:
    slots:
    - honest_broker_subject_id
    - subject_characteristics
    - age_at
    - age_at_normalized
    - age_unit
    - age_precision
    - causative_alteration
    - status
    - genetic_analysis_sample_type
    - laboratory_name
    - cytogenetic_location
    - method
    - gene
    - alteration_type
    - alteration_effect
    - alteration_region
    - hgvs_accession
    - hgvs_coding
    - hgvs_protein
    - hgvs_genomic
    - iscn
    - reported_significance
    - allelic_state
    - maf_numeric
    - mosaicism
    - external_ref_id
    - external_ref_id_system
    comments:
    - 'D4CGNote: One row per subject per method per gene.'
    annotations:
      domain: testing
  Testing:
    slots:
    - honest_broker_subject_id
    - subject_characteristics
    - age_at
    - age_at_normalized
    - age_unit
    - age_precision
    - test_type
    - testing_method
    - testing_measurement_type
    - result_modifier
    - result_numeric
    - result_unit
    - reference_range
    - result_interpretation
    - fasting_status
    - post_glucose_timepoint
    - post_glucose_timepoint_unit
    comments:
    - 'D4CGNote: One row per subject per test type per result.'
    annotations:
      domain: testing
  DiseaseCharacteristics:
    slots:
    - honest_broker_subject_id
    - subject_characteristics
    - age_at
    - age_at_normalized
    - age_unit
    - age_precision
    - diabetes_status
    - hypoglycemia_frequency
    - severe_hypoglycemia_frequency
    - dka
    - time_in_range
    - cgm_range
    - cgm_context
    - diet
    - exercise
    comments:
    - 'D4CGNote: One row per subject per observation.'
    annotations:
      domain: disease_attributes
  Treatment:
    slots:
    - honest_broker_subject_id
    - subject_characteristics
    - age_at_start
    - age_at_start_normalized
    - age_at_stop
    - age_at_stop_normalized
    - age_unit
    - age_precision
    - reason_stop
    - dm_medication_class
    - medication_class_other
    - medication_name
    - medication_code
    - medication_concentration
    - medication_dose
    - medication_unit
    - frequency
    - route
    comments:
    - 'D4CGNote: One row per subject per medication class.'
    annotations:
      domain: intervention
